#!/usr/bin/env node

/* eslint-env node */

/**
 * Automated Setup Script for Inexss CRM
 * 
 * This script automates the entire setup process:
 * 1. Collects Supabase credentials
 * 2. Creates .env file
 * 3. Validates connection
 * 4. Runs database migrations
 * 5. Sets up admin user
 * 6. Verifies setup
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import prompts from 'prompts';
import ora from 'ora';
import chalk from 'chalk';
import { createClient } from '@supabase/supabase-js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

console.log(chalk.bold.cyan('\n🚀 Inexss CRM - Automated Setup\n'));
console.log(chalk.gray('This script will guide you through setting up your CRM in minutes.\n'));

// Helper functions
const success = (msg) => console.log(chalk.green('✓ ' + msg));
const error = (msg) => console.log(chalk.red('✗ ' + msg));
const info = (msg) => console.log(chalk.blue('ℹ ' + msg));
const warn = (msg) => console.log(chalk.yellow('⚠ ' + msg));

async function main() {
  try {
    // Step 1: Check for existing .env
    console.log(chalk.bold('\n📋 Step 1: Environment Configuration\n'));
    
    const envPath = join(__dirname, '.env');
    let supabaseUrl = '';
    let supabaseAnonKey = '';
    
    if (existsSync(envPath)) {
      const envContent = readFileSync(envPath, 'utf8');
      const urlMatch = envContent.match(/VITE_SUPABASE_URL=(.+)/);
      const keyMatch = envContent.match(/VITE_SUPABASE_ANON_KEY=(.+)/);
      
      if (urlMatch && !urlMatch[1].includes('your-project-id')) {
        supabaseUrl = urlMatch[1].trim();
      }
      if (keyMatch && !keyMatch[1].includes('your-anon-key')) {
        supabaseAnonKey = keyMatch[1].trim();
      }
      
      if (supabaseUrl && supabaseAnonKey) {
        info('Found existing Supabase configuration in .env');
        const { useExisting } = await prompts({
          type: 'confirm',
          name: 'useExisting',
          message: 'Use existing Supabase credentials?',
          initial: true
        });
        
        if (!useExisting) {
          supabaseUrl = '';
          supabaseAnonKey = '';
        }
      }
    }
    
    // Collect credentials if not found
    if (!supabaseUrl || !supabaseAnonKey) {
      console.log(chalk.gray('\nYou can find these in your Supabase Dashboard:'));
      console.log(chalk.gray('1. Go to https://app.supabase.com'));
      console.log(chalk.gray('2. Select your project'));
      console.log(chalk.gray('3. Go to Settings > API\n'));
      
      const responses = await prompts([
        {
          type: 'text',
          name: 'url',
          message: 'Enter your Supabase Project URL:',
          initial: supabaseUrl,
          validate: value => {
            if (!value) return 'URL is required';
            if (!value.startsWith('https://')) return 'URL must start with https://';
            if (!value.includes('.supabase.co')) return 'URL must be a Supabase URL';
            return true;
          }
        },
        {
          type: 'text',
          name: 'anonKey',
          message: 'Enter your Supabase anon/public key:',
          initial: supabaseAnonKey,
          validate: value => {
            if (!value) return 'Anon key is required';
            if (!value.startsWith('eyJ')) return 'Anon key should start with "eyJ"';
            return true;
          }
        }
      ]);
      
      if (!responses.url || !responses.anonKey) {
        error('Setup cancelled');
        process.exit(1);
      }
      
      supabaseUrl = responses.url;
      supabaseAnonKey = responses.anonKey;
    }
    
    // Create .env file
    const envContent = `# Supabase Configuration
# Generated by automated setup on ${new Date().toISOString()}

# Your Supabase project URL
VITE_SUPABASE_URL=${supabaseUrl}

# Your Supabase anon/public key
VITE_SUPABASE_ANON_KEY=${supabaseAnonKey}
`;
    
    writeFileSync(envPath, envContent);
    success('.env file created successfully');
    
    // Step 2: Validate connection
    console.log(chalk.bold('\n🔌 Step 2: Validating Supabase Connection\n'));
    
    const spinner = ora('Connecting to Supabase...').start();
    
    let supabase;
    try {
      supabase = createClient(supabaseUrl, supabaseAnonKey);
      
      // Test connection
      const { error: testError } = await supabase.from('users').select('count', { count: 'exact', head: true });
      
      if (testError && !testError.message.includes('does not exist')) {
        throw testError;
      }
      
      spinner.succeed('Successfully connected to Supabase');
    } catch (err) {
      spinner.fail('Failed to connect to Supabase');
      error(err.message);
      error('Please check your credentials and try again');
      process.exit(1);
    }
    
    // Step 3: Database Setup
    console.log(chalk.bold('\n🗄️  Step 3: Database Setup\n'));
    
    info('To complete the setup, you need to run the database migrations in Supabase.');
    info('This will create all necessary tables and configure security policies.');
    
    console.log(chalk.gray('\nPlease follow these steps:'));
    console.log(chalk.gray('1. Open https://app.supabase.com'));
    console.log(chalk.gray('2. Select your project'));
    console.log(chalk.gray('3. Go to SQL Editor'));
    console.log(chalk.gray('4. Click "New Query"'));
    console.log(chalk.gray('5. Copy and run the schema from: supabase/schema.sql\n'));
    
    const { schemaComplete } = await prompts({
      type: 'confirm',
      name: 'schemaComplete',
      message: 'Have you run the schema.sql in Supabase SQL Editor?',
      initial: false
    });
    
    if (!schemaComplete) {
      warn('Please run the database schema before continuing');
      warn('You can run this script again after completing the database setup');
      process.exit(0);
    }
    
    // Verify tables exist
    const verifySpinner = ora('Verifying database tables...').start();
    
    try {
      const tables = ['users', 'brands', 'clients', 'projects', 'meetings'];
      let allTablesExist = true;
      
      for (const table of tables) {
        const { error: tableError } = await supabase.from(table).select('count', { count: 'exact', head: true });
        if (tableError && tableError.message.includes('does not exist')) {
          allTablesExist = false;
          break;
        }
      }
      
      if (allTablesExist) {
        verifySpinner.succeed('Database tables verified successfully');
      } else {
        verifySpinner.warn('Some tables may be missing');
        warn('Please ensure you ran the complete schema.sql file');
      }
    } catch (err) {
      verifySpinner.warn('Could not verify all tables');
    }
    
    // Step 4: Admin User Setup
    console.log(chalk.bold('\n👤 Step 4: Admin User Setup\n'));
    
    info('Setting up admin user: craig@zerobitone.co.za');
    
    console.log(chalk.gray('\nPlease complete admin user creation:'));
    console.log(chalk.gray('1. Go to your Supabase Dashboard'));
    console.log(chalk.gray('2. Navigate to Authentication > Users'));
    console.log(chalk.gray('3. Click "Add User"'));
    console.log(chalk.gray('4. Email: craig@zerobitone.co.za'));
    console.log(chalk.gray('5. Password: (set a secure password)'));
    console.log(chalk.gray('6. ✓ Enable "Auto Confirm User"'));
    console.log(chalk.gray('7. Click "Create User"'));
    console.log(chalk.gray('8. Run the SQL from supabase/setup_admin_user.sql\n'));
    
    const { adminCreated } = await prompts({
      type: 'confirm',
      name: 'adminCreated',
      message: 'Have you created the admin user and run setup_admin_user.sql?',
      initial: false
    });
    
    if (adminCreated) {
      // Verify admin user exists
      const adminSpinner = ora('Verifying admin user...').start();
      
      try {
        const { data: adminData, error: adminError } = await supabase
          .from('users')
          .select('*')
          .eq('email', 'craig@zerobitone.co.za')
          .single();
        
        if (adminError) {
          adminSpinner.warn('Could not verify admin user');
          warn('Please ensure the admin user profile was created in public.users table');
        } else if (adminData && adminData.role === 'admin') {
          adminSpinner.succeed('Admin user verified successfully');
          success(`Name: ${adminData.name}`);
          success(`Email: ${adminData.email}`);
          success(`Role: ${adminData.role}`);
        } else {
          adminSpinner.warn('Admin user found but role is not set to admin');
          warn('Please run setup_admin_user.sql to set the admin role');
        }
      } catch (err) {
        adminSpinner.warn('Could not verify admin user');
      }
    } else {
      info('You can create the admin user later and re-run this script');
    }
    
    // Step 5: Final verification
    console.log(chalk.bold('\n✅ Step 5: Setup Complete!\n'));
    
    success('Environment configured');
    success('Supabase connection verified');
    if (schemaComplete) success('Database schema applied');
    if (adminCreated) success('Admin user created');
    
    console.log(chalk.bold.green('\n🎉 Setup completed successfully!\n'));
    
    console.log(chalk.cyan('Next steps:'));
    console.log(chalk.gray('1. Start the development server: ') + chalk.white('npm run dev'));
    console.log(chalk.gray('2. Open: ') + chalk.white('http://localhost:3000'));
    console.log(chalk.gray('3. Login with: ') + chalk.white('craig@zerobitone.co.za'));
    
    console.log(chalk.cyan('\nUseful commands:'));
    console.log(chalk.gray('  npm run dev     ') + chalk.white('- Start development server'));
    console.log(chalk.gray('  npm run build   ') + chalk.white('- Build for production'));
    console.log(chalk.gray('  npm run verify  ') + chalk.white('- Verify setup'));
    
    console.log(chalk.gray('\nFor help, see: ') + chalk.white('SETUP.md\n'));
    
  } catch (err) {
    error('\nSetup failed: ' + err.message);
    console.error(err);
    process.exit(1);
  }
}

main();
